name: Pre-release Check

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"
      - run: go version
      - run: go mod download
      - run: make docker_build
