name: E2E Test

on:
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"
      - uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - run: go version
      - run: go mod download
      - run: make full_e2e
        env:
          GROCER_BOT_TOKEN: ${{ secrets.GROCER_BOT_TOKEN }}
          E2E_BOT_TOKEN: ${{ secrets.E2E_BOT_TOKEN }}
          E2E_CHANNEL_ID: "904360698140831775"
          E2E_GROCER_BOT_ID: "904359927710113802"
          E2E_GUILD_ID: "815482602278354944"
